# a mybinder.org-ready environment for demoing jupyter_theme_editor
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyter-theme-editor-demo
#
name: jupyter-theme-editor-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=3.0.0,<5.0.0
  # labextension build dependencies
  - nodejs >=16,<17
  - pip
  - wheel
